### PR TITLE
feat: add support for device/folder specific json output

### LINKED ISSUE #4: Add support for json output
I'd really like to use this in scripts which monitor the health of my syncthing devices, and json would make that much more practical.

I took a look at the source and it looks like updating `dash()` to support optional json output would be a significant diff/maybe an ugly big `if` statement. I'm up for taking a shot if that's a PR you'd be open to reviewing

### PR DESCRIPTION
**Pull request by jackmac92**
Added two new commands to get either device or folder info in json format, but it always prints in json. Is that ok with you?

Closes #4

### CODE REVIEW

**Comment by tenox7** [comment]
I don't want to be picky and will accept as is. But consider having just one "jsonDump" function and then have devices and folders as nodes in the json?

**Comment by jackmac92** [comment]
no problem can take a look tomorrow, wanted to send off the initial PR for feedback before I spent more time

thanks for starting this project, looks like it'll be helpful for me!

**Review by tenox7 — APPROVED** [review]
LGTM thank you very much!

**Comment by tenox7** [comment]
again thanks a lot!

please remind me to create a release if I don't do it in a day or two

**Comment by tenox7** [comment]
also could you update readme? thanks

**Comment by tenox7** [comment]
hey I ran it on a mac and getting this:

```
2024/09/21 12:14:19 apikey and target flags not specified, config file: stat /var/folders/mm/vms_5fl93xsdj9038v77jfx80000gn/T/go-build1836372428/b001/exe/config.xml: no such file or directory
```

this doesn't sound right?

**Comment by jackmac92** [comment]
@tenox7 hmm no that doesn't seem correct, I've been running on ubuntu but have a mac machine I can test on and can do some more testing there
I just did a quick test there of cloning the repo and running `go run . json_dump` w/in it, printed the expected json for me.
Could you share the commands you used for testing to try to help me reproduce the issue?

**Comment by jackmac92** [comment]
I think you're hitting that error [here](https://github.com/tenox7/stc/blob/795463468ad2e0a266d3266d5023ad06b6a883ff/stc.go#L372) line 372 before it gets into the `switch flag.Arg(0)`

**Comment by tenox7** [comment]
yeah, but since you're trying to find the config file, could you maybe add to the error that it's not specified and attempt to find automatically it also failed? :)

**Comment by jackmac92** [comment]
Gotcha! I don't think I can expand the error message after a `log.Fatal` 
but can update the existing init on  `cfg`, just need to look into how later

**Comment by jackmac92** [comment]
I wasn't using any env vars/flags to set api auth, just relied on `findCfgFile` so I'm not sure how to make the error more helpful

**Comment by tenox7** [comment]
no worries, I think I can add a better message then release it :)

**Comment by jackmac92** [comment]
@tenox7 thanks for the error update and release!

**Pull request merged**
